repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.3
  hooks:
  - id: gitleaks
- repo: local
  hooks:
  - id: gofmt
    name: gofmt
    entry: bash -c 'gofmt -w "$@" && gofmt -l "$@" | { read && { echo "ERROR: gofmt could not format some files. Check for syntax errors."; exit 1; } || true; }' --
    language: system
    types: [go]
    pass_filenames: true
- repo: https://github.com/golangci/golangci-lint
  rev: v1.52.2
  hooks:
  - id: golangci-lint
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: shellcheck
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
